### ISSUE TITLE
Where to purchase PCA9544A breakout?

### ISSUE THREAD

**Issue by rwaldron** [PulsedLight3D/LIDARLite_MultiSensor_w_PCA9544A_Multiplexer#1]
The diagram in the readme shows a PCA9544A mounted to a PCB—is that the actual component that was used, or just for illustration? Having trouble locating a mounted PCA9544A for this project. Thanks in advance!

**Comment by austinmeyers** [comment]
We got our breakout board from SparkFun and mounted the PCA9544A to it: https://www.sparkfun.com/products/495
